# This file was generated by GoReleaser. DO NOT EDIT.
cask "krmgen" do
  version "2.0.1"

  on_macos do
    on_arm do
      sha256 "bfb2e26d28b2d7fa596bbe7813466d87a22fb7283d5465e96e898562b755b5d5"
      url "https://github.com/librucha/krmgen/releases/download/v#{version}/krmgen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b9bdf0430f560e2d958986e2efde3458369104ba8e5a96999908f1d7334e37b4"
      url "https://github.com/librucha/krmgen/releases/download/v#{version}/krmgen_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3b89343d42d888efd05de609e15f18f362d7ae250df1028d0cca30a732253714"
      url "https://github.com/librucha/krmgen/releases/download/v#{version}/krmgen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0d618c9c4e46d98a4ce374673b5ac345b8e0d65bbb1003617817bfd4133f0843"
      url "https://github.com/librucha/krmgen/releases/download/v#{version}/krmgen_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "krmgen"
  desc "Render Helm charts and Kustomize overlays with Go templates into static Kubernetes YAML"
  homepage "https://github.com/librucha/krmgen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "krmgen"
  bash_completion "completions/krmgen.bash"
  fish_completion "completions/krmgen.fish"
  zsh_completion "completions/krmgen.zsh"

  # No zap stanza required
end
