# This file was generated by GoReleaser. DO NOT EDIT.
cask "krmgen" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "81812cf6b6d734498d99043e7375f0239c70c7b7852208ff16178e6f3b7951a1"
      url "https://github.com/librucha/krmgen/releases/download/v#{version}/krmgen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b27b802ed8651955747459f3031f0d97651ef37638e0d926746a574e503a9dcf"
      url "https://github.com/librucha/krmgen/releases/download/v#{version}/krmgen_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "542bee827625a3a30abbfa18d5e94dac7202c158fa1e7123c7a3b538ed23a00e"
      url "https://github.com/librucha/krmgen/releases/download/v#{version}/krmgen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3c71c796981fd2eb486ce200b98617a6b36e7ff04d63bd7097979ea552a6ef6a"
      url "https://github.com/librucha/krmgen/releases/download/v#{version}/krmgen_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "krmgen"
  desc "Render Helm charts and Kustomize overlays with Go templates into static Kubernetes YAML"
  homepage "https://github.com/librucha/krmgen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "krmgen"

  # No zap stanza required
end
