# This file was generated by GoReleaser. DO NOT EDIT.
cask "krmgen" do
  version "1.0.4"

  on_macos do
    on_arm do
      sha256 "fb120f0a406557c4c8d1cc15808485c6684d1a01f556367141ec14a784c0fe8e"
      url "https://github.com/librucha/krmgen/releases/download/v#{version}/krmgen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9a48006ba6cc73e9af7237b6c9c9cd89173d85b54ba92e1ec56f38e1287395cc"
      url "https://github.com/librucha/krmgen/releases/download/v#{version}/krmgen_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "acda8311fca569e5aec062ba72d7c83fad5e0ee78bee05cfa43af1444a1bde5f"
      url "https://github.com/librucha/krmgen/releases/download/v#{version}/krmgen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e06ad99d7dd7fbea1053d1aaafaf51664a3a1dfb7f6ff253a7e2cf81b24881aa"
      url "https://github.com/librucha/krmgen/releases/download/v#{version}/krmgen_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "krmgen"
  desc "Render Helm charts and Kustomize overlays with Go templates into static Kubernetes YAML"
  homepage "https://github.com/librucha/krmgen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "krmgen"

  # No zap stanza required
end
